name: deploy-all
on:
  push:
    paths:
      - '**'
      - '!README.md'

jobs:
  deploy-all:
    runs-on: ubuntu-latest

    steps:
      
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}


    - name: Configure environment name
      id: env-name
      env:
        REPO: ${{ github.repository }}
      run: |
        ENVIRONMENT=`echo $REPO | tr "/" "-"`
        echo "Environment name: $ENVIRONMENT"
        echo "::set-output name=environment::$ENVIRONMENT"

    - name: Deploy Cloudformation Templates
      env:
        EnvironmentName: ${{ steps.env-name.outputs.environment }}
        BUCKET_NAME: ${{ secrets.TOBE_CREATED_BUCKET_NAME }}
      run: |
        chmod +x *.sh
        ./one-click.sh  ${BUCKET_NAME}

